[tool.briefcase]
project_name = "Score Keeper"
bundle = "com.example"
version = "0.0.1"
url = "https://github.com/pauldjackson70/scorekeeper"
license = "BSD license"
author = 'Paul D Jackson'
author_email = "paul.d.jackson70@gmail.com"

[tool.briefcase.app.scorekeeper]
formal_name = "Score Keeper"
description = "A program to keep track of score during game play"
icon = "src/scorekeeper/resources/scorekeeper"
sources = ['src/scorekeeper']
requires = []


[tool.briefcase.app.scorekeeper.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.scorekeeper.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.scorekeeper.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.scorekeeper.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.scorekeeper.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
